### ISSUE TITLE
Error:Project :app declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :rn-live.

### ISSUE THREAD

**Issue by i3i2uno** [devhuyhq/RNLive#1]
Any insight on why I might be receiving this issue on Android? I can't get Android Studio to sync the  gradle no matter what I try...

`Error:Project :app declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :rn-live.`

**Comment by sagar1garg** [comment]
@i3i2uno what was the solution? I am also getting the below error. Any resolution?
Could not find com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:1.3.8.
           Required by:
               screen:rn-live:unspecified

**Comment by ycc2017x** [comment]
@sagar1garg I am not sure that this is the same error that you are seeing, but basically the problem for me was the android folder in this project was setup as a project instead of a module. I have since forked this project and have fixed a number of bugs and got it working. Give it a try:

https://github.com/i3i2uno/RNLive

**Comment by i3i2uno** [comment]
@sagar1garg I am not sure that this is the same error that you are seeing, but basically the problem for me was the android folder in this project was setup as a project instead of a module. I have since forked this project and have fixed a number of bugs and got it working. Give it a try:

https://github.com/i3i2uno/RNLive

**Comment by sagar1garg** [comment]
Thanks for sharing the link. Also I found that replacing 
project(':rn-live').projectDir = new File(rootProject.projectDir, '../node_modules/rn-live/android'
with 
project(':rn-live').projectDir = new File(rootProject.projectDir, '../node_modules/rn-live/android/app' 
got rid of the initial errors.
I think you forgot to change the npm path to the project in the readme. The npm install --save rn-live command is for the original project

**Comment by i3i2uno** [comment]
Yea sorry I wasn't clear about that. I haven't edited the readme. Basically what I meant is if you replace rn-live with this in your projects package.json file:

`"rn-live": "git+https://github.com/i3i2uno/RNLive.git",`

Then follow the rest of the steps in the readme it should get setup.

**Comment by sagar1garg** [comment]
Isn't working that way. I think either you will need to make it a proper npm module or leave it as a project which we can download and install

**Comment by i3i2uno** [comment]
Not sure what to tell you. I am doing clean npm installs with this forked git module, after following the manual install directions listed in the readme and it is working. Has been working for the last 4 months. Which platform is it not working for you on? What is the error(s) you are getting?

**Comment by sagar1garg** [comment]
I included all files in my project and got it running but I was testing it using the example app.js file with DaCast and there was no live stream visible from my phone. Have you tested it with any live streaming solutions?

**Comment by i3i2uno** [comment]
Yea. You can actually check out my app live on the [app store](https://itunes.apple.com/us/app/sunspot-media/id1276072090?mt=8) or the [play store](https://play.google.com/store/apps/details?id=com.sspot) and after logging in create a room/spot and then click bottom right three dots and do "start live stream". 

The way it actually works is, I used rn-live to stream the audio/video and send it to a rtmp publishing server. Where I used [node-media-server](https://www.npmjs.com/package/node-media-server) to then broadcast the rtmp stream to others. When using the node-media-server you can see if the connection and broadcast is successful, then you can watch it from other devices just for test case by using vlc player, and just pointing the connection to the node-media-server endpoint.

You also don't have to use your own media server, you can potentially use rn-live to send the stream to any other cloud based streaming solutions like wowza or akami

**Comment by sagar1garg** [comment]
Great job with your app! 

I am looking to live stream the Mobile screen along with the audio. For example if I'm playing a video on the phone then the video with it's audio should be streamed. Plus I wish to overlay my commentary for that video. Is this supported?
Also is it possible for you to share just the node-media-server connection file with me?

**Comment by i3i2uno** [comment]
So my actual controller for the node-media-server is not much different than what they have listed as an example:

```
nms.run();
nms.on('preConnect', (id, args) => {
  console.log('[NodeEvent on preConnect]', `id=${id} args=${JSON.stringify(args)}`);
  // let session = nms.getSession(id);
  // session.reject();
});

nms.on('postConnect', (id, args) => {
  console.log('[NodeEvent on postConnect]', `id=${id} args=${JSON.stringify(args)}`);
});

nms.on('doneConnect', (id, args) => {
  console.log('[NodeEvent on doneConnect]', `id=${id} args=${JSON.stringify(args)}`);
});

nms.on('prePublish', (id, StreamPath, args) => {
  console.log('[NodeEvent on prePublish]', `id=${id} StreamPath=${StreamPath} args=${JSON.stringify(args)}`);
  // let session = nms.getSession(id);
  // session.reject();
});

nms.on('postPublish', (id, StreamPath, args) => {
  console.log('[NodeEvent on postPublish]', `id=${id} StreamPath=${StreamPath} args=${JSON.stringify(args)}`);
});

nms.on('donePublish', (id, StreamPath, args) => {
  console.log('[NodeEvent on donePublish]', `id=${id} StreamPath=${StreamPath} args=${JSON.stringify(args)}`);
});

nms.on('prePlay', (id, StreamPath, args) => {
  console.log('[NodeEvent on prePlay]', `id=${id} StreamPath=${StreamPath} args=${JSON.stringify(args)}`);
  // let session = nms.getSession(id);
  // session.reject();
});

nms.on('postPlay', (id, StreamPath, args) => {
  console.log('[NodeEvent on postPlay]', `id=${id} StreamPath=${StreamPath} args=${JSON.stringify(args)}`);
});

nms.on('donePlay', (id, StreamPath, args) => {
  console.log('[NodeEvent on donePlay]', `id=${id} StreamPath=${StreamPath} args=${JSON.stringify(args)}`);
});
```

Just go to their github page and check out the examples. There are quite a few. RN-Live plugs in quite easily: [https://github.com/illuspas/Node-Media-Server](https://github.com/illuspas/Node-Media-Server)

All you will essentially have to do is have a node server running, with the node-media-server plugged in, it will output debug info in the console. RTMP servers are typically on port 1935, so with RN-live running you will just point your url to http://localhost:1935/room/mystream or something like that, and then node-media-server will start the broadcast.

You should be able to do what you are talking about. Although this library is intended to stream the video from the camera. Not a screen capture. Though I think you could easily fork this and do something very similar, but you will have to dive into native code. Or find another library that already does that, I'm sure there is something close already out there. 

Best of Luck

**Comment by sagar1garg** [comment]
@i3i2uno Hi Bruce. I tried node media server but it seems it does not support multicasting. I did a local test with 4-5 phones and it denied access to streams if more than 1 client is requesting it. Did you face the same or did it perform multicast well for you? If you did face the same how did you solve it?
